[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "twin-file-detective"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "xxhash>=3.6.0",
]

[tool.setuptools]
py-modules = ["main", "functions"]

[project.scripts]
twin-file-detective = "main:main"